version: '3.8'

services:
  netcheck:
    image: netcheck:own  # Adjust if your image has a different name/tag
    container_name: netcheck_monitor  # Optional but descriptive
    restart: always
    ports:
      - "9000:9000"  # Maps host port 9000 to container port 9000

    environment:
      TZ: "Europe/Vienna"  # Set the timezone; see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      NETCHECK_DISABLE_SPEEDTEST: "true"  # If true, disables speed tests after reconnect/start
